baseURL = "https://meshdb.io/"
languageCode = "en-us"
title = "MeshDB"
theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      title = "MeshDB"
      description = "MeshDB — a modern graph database."

[menu]
  [[menu.main]]
    name = "Documentation"
    weight = 10
    url = "/docs/"
  [[menu.main]]
    name = "Blog"
    weight = 20
    url = "/blog/"
  [[menu.main]]
    name = "GitHub"
    weight = 30
    url = "https://github.com/mesh-db/mesh"

[params]
  copyright = "The MeshDB Authors"

  version_menu = "Releases"
  version = "0.2"
  url_latest_version = "https://meshdb.io"

  github_repo = "https://github.com/mesh-db/mesh"
  github_project_repo = "https://github.com/mesh-db/mesh"

  offlineSearch = true
  prism_syntax_highlighting = false

  [params.taxonomy]
    taxonomyCloud = ["tags", "categories"]
    taxonomyCloudTitle = ["Tag Cloud", "Categories"]
    taxonomyPageHeader = ["tags", "categories"]

  [params.ui]
    breadcrumb_disable = false
    navbar_logo = true
    sidebar_menu_compact = false
    sidebar_search_disable = false
    showLightDarkModeMenu = true

  [params.ui.feedback]
    enable = true
    yes = 'Glad to hear it! Please <a href="https://github.com/mesh-db/mesh/issues/new">tell us how we can improve</a>.'
    no = 'Sorry to hear that. Please <a href="https://github.com/mesh-db/mesh/issues/new">tell us how we can improve</a>.'

  [[params.links.user]]
    name = "GitHub Discussions"
    url = "https://github.com/mesh-db/mesh/discussions"
    icon = "fab fa-github"
    desc = "Discussion and help from your fellow users"
  [[params.links.developer]]
    name = "GitHub"
    url = "https://github.com/mesh-db/mesh"
    icon = "fab fa-github"
    desc = "Development takes place here!"
  [[params.links.developer]]
    name = "GitHub Issues"
    url = "https://github.com/mesh-db/mesh/issues"
    icon = "fas fa-bug"
    desc = "Report bugs or request features"
